#!/usr/bin/env bash
#
# Git clone/push monitoring
#
# Usage: ./check_git url password private_key_file
#
# Description:
#
# Attempts a clone of a remote repository URL. If username/password/private_key_file
# are provided, then it will attempt to push back to the repo.
#
# Output:
#
# Returns OK state if the clone (and push, if requested) succeed.
#
# Examples:
#
# git URL:
#   check_git git://git.drupal.org/rfay/sandbox/11010.git
# ssh URL:
#   check_git testuser@git.drupal.org:rfay/sandbox/11010.git --key /path/to/id_file
# ssh URL including a commit and a push:
#   check_git testuser@git.drupal.org:rfay/sandbox/11010.git --key /path/to/id_file --push
#
# If a writable git URL is provided, it's assumed to be a test-only repository,
# and it will grow, of course.

PROGNAME=${0##*/}
PROGPATH=${0%/*}
REVISION='0.1.1'
export PATH=/usr/local/bin:/usr/bin:/bin
export TMPDIR=/tmp

# Try to load the Nagios plugin utility library.  If we don't find it,
# exit with an error.
for d in $PROGPATH /usr/lib64/nagios/plugins /usr/lib/nagios/plugins /usr/local/libexec/nagios; do
    [[ -f $d/utils.sh ]] && . $d/utils.sh
done

if [[ -z "$STATE_OK" ]]; then
    # We hardcode an exit w/the STATE_UNKNOWN value if we can't find
    # the plugin utility library.
    echo "No Nagios plugin utility library was found; exiting"
    exit 4
fi

# Directory to use to create the repo
REPO_DIR=$(mktemp -d $TMPDIR/$PROGNAME.XXXXXXXXXXXX)
if [[ ! -d $REPO_DIR ]]; then
    echo "Could not create a temporary directory for the git repo; exiting"
    exit $STATE_UNKNOWN
fi
GIT_SSH=$(tempfile -d ~/.ssh --prefix git. --suffix .ssh -m 700)
if [[ ! -x $GIT_SSH ]]; then
    echo "Could not create a temporary git-ssh file; exiting"
    exit $STATE_UNKNOWN
fi
trap "rm -Rf $REPO_DIR; rm -f $GIT_SSH" EXIT

print_usage() {
    echo "Usage: $PROGNAME repo_url [ --keyfile /path/to/id_file ] [ --push ]"
    echo "Usage: $PROGNAME --help"
    echo "Usage: $PROGNAME --version"
}

print_help() {
    print_revision $PROGNAME $REVISION
    echo ""
    print_usage
    echo ""
    echo "Git remote repo checker for Nagios"
    echo ""
    support
}

# Make sure the correct number of command line
# arguments have been supplied

if [ $# -lt 1 ]; then
    print_usage
    exit $STATE_UNKNOWN
fi

# Grab the command line arguments
exitstatus=$STATE_WARNING #default
while test -n "$1"; do
    case "$1" in
        --help|-h)
            print_help
            exit $STATE_OK
            ;;
        --version|-v)
            print_revision $PROGNAME $REVISION
            exit $STATE_OK
            ;;
        --keyfile|--key|-k)
            keyfile=$2
            shift

            echo "ssh -T -o StrictHostKeyChecking=no -i $keyfile \$*" > $GIT_SSH
            export GIT_SSH
            ;;
        --push)
            push=1
            ;;
        --exitstatus)
            exitstatus=$2
            shift
            ;;
        -*)
            echo "Unknown argument: $1"
            print_usage
            exit $STATE_UNKNOWN
            ;;
        *)
            repo=$1
            ;;
    esac
    shift
done

# Use git ls-remote if not testing push
if [ "$push" == "" ]; then
    OUTPUT="git ls-remote $repo HEAD
      $(git ls-remote $repo HEAD 2>&1)"
    GIT_CLONE_RESULT=$?
else
    OUTPUT="git clone $repo $REPO_DIR
      $(git clone $repo $REPO_DIR 2>&1)"
    GIT_CLONE_RESULT=$?
fi

if [ "$GIT_CLONE_RESULT" = "0" ]; then
    exitstatus=$STATE_OK
elif [ "$GIT_CLONE_RESULT" = "2" ]; then
    exitstatus=$STATE_WARNING
    exit $exitstatus
else
    echo "Failed operation: $OUTPUT"
    exitstatus=$STATE_CRITICAL
    exit $exitstatus
fi

# attempt a push here
if [ "$push" != "" ]; then
    export GIT_WORK_TREE=$REPO_DIR
    export GIT_DIR=$REPO_DIR/.git
    echo "Committed by Nagios on $(hostname) check_git: $(date)" >> $GIT_WORK_TREE/check_git_commits.txt
    git add .
    NOW=$(date)
    ERROR=$(git commit -m "Test commit by check_git $NOW")
    OUTPUT="$OUTPUT
      $ERROR"
    ERROR="$(git push 2>&1)"
    GIT_PUSH_RESULT=$?
    OUTPUT="$OUTPUT
     $ERROR"
    if [ "$GIT_PUSH_RESULT" = "0" ]; then
        exitstatus=$STATE_OK
    else
        exitstatus=$STATE_CRITICAL
    fi
fi

echo "$OUTPUT"
exit $exitstatus;

# Copyright (c) 2011, 2012 Randy Fay and Mark Waite

# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:

# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
